employees/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('list/',views.employee_list, name='employee_list'),
    path('table/',views.employee_tbl, name='employee_Table'),
    path('<int:emp_id>/detail',views.employee_detail, name='employee_detail'),
    path('emp_add/',views.employee_add, name='employee_add'),
    path('<int:emp_id>/edit',views.employee_update,name='employee_update'),
]

salary_and_ts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from searches.views import search_view, load_emp
from timesheets.views import GrpTimesheet_view, timesheet_save, Sgltimesheet_view, NappTsTbl_view, approveTS_view, timesheetSearch_view
from vacations.views import vacation_view, vacation_apporveList_view, vacation_apporve_view, vacationSearch_view
from settings.views import NaVaction_view, Workingday_view, OverTime_view, TravelAllowance_view, TaxRate_view, SocialInsurance_view, HealthInsurance_view, Shifts_view, SingleMultiUser_view, Department_view
from authen.views import home_view, signup_view, secure_view, SecurePage_view
from Salary.views import AnnualIncrease_view, SaveAnnualIncrease_view, MonthlyBonusPenalty_view, MonthlyBonusPenaltyList_view, EmpSalaryDetail_view, AllSalaryList_view, AllSalaryList_MultiTbl_view, EmpSalaryDetailLink_view
from finger_print.views import export_view, import_view 
urlpatterns = [
    # authen
    path('',home_view, name='home'),
    path('secure',secure_view, name='secure'),
    path('secure2', SecurePage_view.as_view(), name='secure2'),
    path('signup/',signup_view, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    #employees
    path('emp/',include('employees.urls')),
    #timesheets
    path('GrpTimesheet/', GrpTimesheet_view),
    path('ajax/save_ts/',timesheet_save, name='saveTimesheet'),
    path('SglTimesheet/', Sgltimesheet_view),
    path('NappTsTbl/', NappTsTbl_view),
    path('<int:emp_id>/approveTS/',approveTS_view, name='approveTimesheet'),
    path('timesheet/<int:TVdate_month>/<int:TVdate_Year>/<int:emp_ID>',timesheetSearch_view ),
    #vacations
    path('vacationForm/', vacation_view),
    path('vacationApproveList/', vacation_apporveList_view),
    path('<int:emp_id>/<int:req_num>/vacationApprove/',vacation_apporve_view, name ='approveVacation' ),
    path('vacation/<int:TVdate_Year>/<int:emp_ID>', vacationSearch_view),
    #settings
    path('NaVaction/',NaVaction_view),
    path('WorkDay/',Workingday_view),
    path('SingleMultiUser/',SingleMultiUser_view),
    path('OverTime/',OverTime_view),
    path('TravelAllowance/',TravelAllowance_view), 
    path('TaxRate/',TaxRate_view), 
    path('SocialInsurance/',SocialInsurance_view), 
    path('HealthInsurance/',HealthInsurance_view), 
    path('Shifts/',Shifts_view),
    path('Department/', Department_view),
    #search
    path('search/', search_view),
    path('ajax/load-emp/', load_emp , name='ajax_load_emp'),
    #salary
    path('AnInc/',AnnualIncrease_view),
    path('SaveAnInc/',SaveAnnualIncrease_view),
    path('MoBoPe/',MonthlyBonusPenalty_view),
    path('tblBonus/',MonthlyBonusPenaltyList_view, name='Bonus_Table'),
    path('EmpSalDet/',EmpSalaryDetail_view, name = 'EmpSalaryDetail'),
    path('<int:emp_id>/<str:SDate>/EmpSalDetLink/', EmpSalaryDetailLink_view, name= 'EmpSalaryDetailLink'),
    path('EmpSalList/',AllSalaryList_view, name ='AllSalaryList'),
    path('EmpSalListMT/',AllSalaryList_MultiTbl_view, name='AllSalaryList_MultiTbl'),
    #finger_print
    path('import/',import_view),
    path('export/',export_view, name= 'export'),
    #select2
    path('select2/', include('django_select2.urls')),
    #admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    #test mode not live
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timesheets/models.py
from django.db import models
from django.conf import settings
from employees.models import Department, Employee, Profile
from Salary.fun_SingleMultiUser import SingleMultiUser_fun


class TimeSheet(models.Model):
    Working_Hour_CHOISES =(    #to make salary_base choice without foreignkey in models
        ('8','Full_day'),
        ('4','Half_day'),
        ('0','absent')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    Emp_name =  models.ForeignKey(Employee,null=True, on_delete=models.CASCADE )
    Pro_name =  models.ForeignKey(Profile,null=True, on_delete=models.CASCADE )
    Department = models.ForeignKey(Department,null=True, on_delete= models.CASCADE )
    Date = models.DateField(auto_now=False)
    working_hour = models.IntegerField(null=True, blank=True ,choices=Working_Hour_CHOISES)
    submit_date=models.DateTimeField(auto_now=False, null=True, blank=True )
    approve_date=models.DateTimeField(auto_now=False, null=True, blank=True)
    #overtime_hour = models.DecimalField(decimal_places= 0, max_digits= 2,blank=True, null=True)
    #alowance_category= models.DecimalField(decimal_places= 0, max_digits=2, blank=True, null=True)
    #bonus = models.DecimalField(decimal_places= 0, max_digits=2, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['Emp_name','Pro_name','Date'],name='unique_timesheet')
            #each employee have only one timesheet each day 
        ]
    if SingleMultiUser_fun() == Employee:
        def __str__(self):
            return self.Emp_name.Full_name
    
    elif SingleMultiUser_fun() == Profile:
        def __str__(self):
            return self.Pro_name.Full_name.username

Salary/forms.py
from django import forms
from django_select2.forms import Select2Widget
from django.forms import ModelChoiceField, widgets, SelectDateWidget, DateInput, NumberInput, TextInput
from .models import MonthlyBonusPenalty 
from employees.models import Employee, Department, Profile
from django.contrib.auth.models import User
from Salary.fun_SingleMultiUser import SingleMultiUser_fun #the system refuser to load it here as there is circular import issue
from settings.models import SingleMultiUser

class MonthlyBonusPenaltyForm(forms.Form):
    departement = forms.ModelChoiceField(
        queryset=Department.objects.all(),
        widget=Select2Widget(attrs={'data-placeholder':(u"Departement")})
        ,required = True
        )
    employee_list = forms.ModelChoiceField(
        queryset=SingleMultiUser_fun().objects.none(),   
        widget=Select2Widget(attrs={'data-placeholder':(u"Employee_Name"), 'class':'vac_emp_name'}) 
        ,required = False
        )
    bonus=  forms.FloatField(
        widget=NumberInput(attrs={'class': 'form-control '},)
        )
    penalty= forms.FloatField(
        widget=NumberInput(attrs={'class': 'form-control '},)
        )
    date= forms.DateField(
        input_formats = ['%Y-%m-%d'],
        widget = DateInput(attrs={'class': 'form-control ', 'type':'date'}, )
        ,required = True
        )
    reason= forms.CharField(
        widget = TextInput(attrs={'class': 'form-control '}, )
        )
    
    
       
    def __init__(self, *args, **kwargs): #we do this because the form.is_valid() is always False and the emp is always empty. dependent dropdown list
        super().__init__(*args, **kwargs)
    

        if 'departement' in self.data:
            try:
                Department_id= int(self.data.get('departement'))
                self.fields['employee_list'].queryset = Employee.objects.filter(Department_id=Department_id).order_by('id')
            except(ValueError,TypeError):
                pass
        elif self.instance.pk:  #there is no update in that form
            self.fields['employee_list'].queryset = self.instance.Departement.Employee_set.order_by('id')

class MonthlyBonusPenaltyFormModel(forms.ModelForm):
    #that is how to make union for the employee but we will not use it as we need all employee in one select and then to be save in 2 diferent field 
    employee_name= forms.ModelChoiceField(label= 'Employee with no TS access',queryset=Employee.objects.all().values_list('Full_name',flat=True).union(User.objects.all().values_list('username',flat=True)), widget=Select2Widget(attrs={'data-placeholder':(u"Choose one ")}))
    #that is how we can make the below field foreign key field apear in a specific order
    employee_name_Pro = forms.ModelChoiceField(label= 'Employee with TS access',queryset=Profile.objects.all().order_by('Full_name_id'), widget=Select2Widget(attrs={'data-placeholder':(u"Choose one")}))
    class Meta:
        model = MonthlyBonusPenalty
        fields = ['employee_name','employee_name_Pro', 'bonus', 'penalty', 'date', 'reason']
        exclude = ()
        widgets={
            'date' : DateInput(attrs={'class': 'form-control ', 'type':'date' },),
            # 'employee_name' :Select2Widget(attrs={'data-placeholder':(u"Employee_Name")}) ,
            # 'employee_name_Pro':Select2Widget(attrs={'data-placeholder':(u"(attrs={'data-placeholder':(u"Employee_Name")})")}) ,
            'numDay' : NumberInput (attrs={'class': 'form-control ' },),
            
        }


class MonthlyBonusPenaltyForm1(forms.Form):
    
    employee_list = forms.ModelChoiceField(
        label='Employee Name',
        queryset= SingleMultiUser_fun().objects.all().order_by('pk'),#Employee.objects.all().values_list('Full_name',flat=True).union(User.objects.all().values_list('username',flat=True).exclude(username__icontains ='admin')).exclude(Full_name__icontains ='admin'),   
        widget=Select2Widget(attrs={'data-placeholder':(u"Employee_Name")}) 
        ,required = True,
        #to_field_name="Full_name"
        )
    bonus=  forms.FloatField(
        widget=NumberInput(attrs={'class': 'form-control '},)
        ,required = False
        )
    penalty= forms.FloatField(
        widget=NumberInput(attrs={'class': 'form-control '},)
        ,required = False
        )
    date= forms.DateField(
        input_formats = ['%Y-%m-%d'],
        widget = DateInput(attrs={'class': 'form-control ', 'type':'date'}, )
        ,required = True
        )
    reason= forms.CharField(
        widget = TextInput(attrs={'class': 'form-control '}, )
        ,required = False
        )

timesheets/templates/timesheets/NATSList.html
{%extends "base.html"%}
{%load render_table from django_tables2 %}
{%block title %} {{title}} {%endblock%}


{%block body1 %}
<h2 class="font-weight-normal text-center border border-secondary rounded">{{title}}</h2> 
{% csrf_token %}
<div style='display:none' id='empID'>{{qs.id}}</div>
{%if NAEmpTs%}
<div class = 'container-fluid'>
    <div class ='row my-auto py-auto'>
            <div class=' col-6 mx-auto'>
                <button type="button" class="btn btn-outline-primary ApTblEmp" id='approve' >Approve</button>
                <button type="button" class="btn btn-outline-secondary ApTblEmp" id='reject' >Reject</button>
            </div>
            <div class=' col-3 '>
                    <div class="font-weight-bolder text-center border border-primary rounded ">Time Sheet status:</div>
            </div>
            <div class=' col-3 '>        
                    <div class="font-weight-normal text-center border border-secondary rounded" id='TS_stat'> Not approved </div>
            </div>
    </div>
</div>
{%endif%}

{%if message%}
<h4>{{message}}</h4>
{%endif%}

{%if table%}
{%render_table table %}
{%endif%}


{%endblock%}

timesheets/templates/timesheets/grpTS.html
{%extends "base.html"%}
{%load render_table from django_tables2 %}
{%block title %} Grp_timesheets {%endblock%}


{%block body1 %}
<h2 class="font-weight-normal text-center border border-secondary rounded">timesheets_Group-Employee_per/day__sorted by_{{sort_by}}</h2> 
{% csrf_token %}
<div class='container-fluid'>
    <div class='row'>
        <div class='col-4 text-left'>
            date of today
        </div>
        <div class='col-4 text-center' id='NowDate'>
            {{nows|date:"D d M Y" }}-{{nows|time:"H:i"}}
        </div>
        <div class='col-4 text-right'>
            تاريخ اليوم 
        </div>
    </div>
</div>
 <br>
<div class='container'>
    <div class='row'>
        
        <div class=' col-4 text-left'>Timesheet date: </div>
        <div class=' col-4 text-center'>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <!--<button class="btn btn-outline-primary" type="button" id="Sr_TS_date">Search</button>-->
                </div>
                <input id='TS_date' name='TS_date' type='date' class="form-control"  aria-label="Example text with button addon" aria-describedby="button-addon1"> <!--value= "{{nows|date:"Y-m-d"}}"-->
            </div>
        </div>
        <div class=' col-4 text-right'>التاريخ </div>
    </div>
</div>

<div class = 'container-fluid'>
    <div class ='row my-auto py-auto'>
            <div class=' col-6 mx-auto'>
                <button type="button" class="btn btn-outline-primary SaSuApTblAllEmp" id='SaveTblAllEmp' disabled>Save</button>
                <button type="button" class="btn btn-outline-secondary SaSuApTblAllEmp" id='SubAppTblAllEmp' disabled>submit/apporve</button>
            </div>
            <div class=' col-3 '>
                    <div class="font-weight-bolder text-center border border-primary rounded ">Time Sheet status:</div>
            </div>
            <div class=' col-3 '>        
                    <div class="font-weight-normal text-center border border-secondary rounded" id='TS_stat'> Unknown </div>
            </div>
    </div>
</div>


{%render_table table %}



{%endblock%}

timesheets/templates/timesheets/singleTs.html
{%extends "base.html"%}
{%load grp_extras %}

{%block title %} Single_timesheets {%endblock%}


{%block body1 %}

{%if data.error_message%}
<h4 class="font-weight-normal text-center border border-secondary rounded">timesheets_for employee : <b>{{data.Emp_name}}</b>  for Month: <b>{{data.TSDates|date:"F"}}/{{data.TSDates|date:"Y"}}</b> </h4> 
<div style='color:red'>{{data.error_message}}</div>
{%elif data.TSDates%}
<h4 class="font-weight-normal text-center border border-secondary rounded">timesheets_for employee : <b>{{data.Emp_name}}</b>  for Month: <b>{{data.TSDates|date:"F"}}/{{data.TSDates|date:"Y"}}</b> </h4> 
<div id='emp_name' style='display:none'>{{data.Emp_name.id}}</div>
<div id='TSMonth' style='display:none'>{{data.TSMonth}}</div>
<div id='TSYear' style='display:none'>{{data.TSYear}}</div>
{%else%}
<h4 class="font-weight-normal text-center border border-secondary rounded">timesheets_for employees per month </h4> 
{%endif%}
<form   method="post" class="form-inline my-2 my-lg-0" id="empByDep" data-emp-url="{% url 'ajax_load_emp' %}" action= '' >
    {% csrf_token %}
    {%if request.user|has_group:"Self Timesheet and Vacation Request"%}
    <input id="id_employee_list" name= "employee_list"  value = '{{user.id}}' style='display:none' >
    
    {%else%}
    <div class= 'form control mr-sm-2' >{{form.departement}} </div>
    <div class= 'form control mr-sm-2' >{{form.employee_list}} </div>
    {%endif%}
    <div class= 'form control mr-sm-2' >{{form.TSdate}} </div>
    
    <button class='btn btn-outline-success my-2 my-sm-0' id='SrSgTS' type='submit'>Search</button>
  </form>
  
  
<br> <br>
<div class = 'container-fluid'>
    <div class ='row my-auto py-auto'>
            <div class=' col-6 mx-auto'>
                {%if data.TS_status == 'created' or data.TS_status == 'not created yet' %}
                <button type="button" class="btn btn-outline-primary SaSuTblEmp" id='SaveTblEmp' >Save</button>
                <button type="button" class="btn btn-outline-secondary SaSuTblEmp" id='SubTblEmp' >submit</button>
                {%else%}
                <button type="button" class="btn btn-outline-primary SaSuTblEmp" id='SaveTblEmp' disabled>Save</button>
                <button type="button" class="btn btn-outline-secondary SaSuTblEmp" id='SubTblEmp' disabled>submit</button>
                {%endif%}
              </div>
            <div class=' col-6 mx-auto '>
                    <div class="font-weight-normal text-center border border-secondary rounded">Time Sheet status: <b>{{data.TS_status}}</b></div>
            </div> 
            
      </div>
</div>
<table class="table">
    <thead>
      <tr>
        <th scope="col"> #</th>
        <th scope="col">day #</th>
        <th scope="col">day Name</th>
        <th scope="col">Working Hour</th>
        <th scope="col">Allowance</th>
        <th scope="col">Overtime</th>
      </tr>
    </thead>
    <tbody>
      
      {% if data.qs != 'None'  %}
        {% for x in data.qs %}
          {% if x.Date|date:"l" in data.weekEnd %}
              <tr style='color:red'>
          {%else%}
              <tr>
          {%endif%}
          
                <th scope="row">{{ x.Date.day }}</th>
                <td> {{ x.Date.day }} </td>
                <td> {{ x.Date|date:"l" }} </td>
                
                <td>
                  {% if x.Date in data.apExVac and x.Date in data.apVac %}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' selected>approved Extra vacation</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8' >Full_day</option>
                    </select>
                  {%elif x.Date not in data.apExVac and x.Date in data.apVac %}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' >absent</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8' selected >approved vacation</option>
                    </select>
                    {%elif x.Date|date:"l" in data.weekEnd%}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' selected >Week End</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8'>Full_day</option>
                    </select>
                    {%elif x.Date in data.NVac%} <!--we put national vacation 0 as working in this day will be overtime-->
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' selected >National vacation</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8'>Full_day</option>
                    </select>
                  {%else%}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' {%if data.TS_status == 'submited' or data.TS_status == 'approved' %} disabled {%endif%} >
                      <option value=''></option>
                      <option value='0' id='0' {% if x.working_hour == 0 %}selected{%endif%} >absent</option>
                      <option value='4' id='4' {% if x.working_hour == 4 %}selected{%endif%} >Half_day</option>
                      <option value='8' id='8' {% if x.working_hour == 8 %}selected{%endif%} >Full_day</option>
                    </select>
                  {%endif%}
                </td>
                <td>--</td>
                <td>--</td>
              </tr>
        {%endfor%} 
      {%else%}
        {% for x in month_days %}
          {% if x|date:"l" in data.weekEnd %}
            <tr style='color:red'>
          {%else%}
            <tr>
          {%endif%}
            
              <th scope="row">{{ x.day }}</th>
              <td> {{ x.day }} </td>
              <td> {{ x|date:"l" }} </td>
              
              <td>
                
                  {% if x in data.apExVac and x in data.apVac %}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' selected>approved Extra vacation</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8' >Full_day</option>
                    </select>
                  {%elif x not in data.apExVac and x in data.apVac %}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                      <option value=''></option>
                      <option value='0' id='0' >absent</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8' selected >approved vacation</option>
                    </select>
                  {%elif x|date:"l" in data.weekEnd%}
                  <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                    <option value=''></option>
                    <option value='0' id='0' selected >Week End</option>
                    <option value='4' id='4'>Half_day</option>
                    <option value='8' id='8'>Full_day</option>
                  </select>
                  {%elif x in data.NVac%} <!--we put national vacation 0 as working in this day will be overtime-->
                  <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' disabled >
                    <option value=''></option>
                    <option value='0' id='0' selected >National vacation</option>
                    <option value='4' id='4'>Half_day</option>
                    <option value='8' id='8'>Full_day</option>
                  </select>
                  {%else%}
                    <select maxlenght='10' name='Working_Hour' class="btn btn-outline-primary Working_Hour" data-placeholder='choose one' >
                      <option value=''></option>
                      <option value='0' id='0'>absent</option>
                      <option value='4' id='4'>Half_day</option>
                      <option value='8' id='8'>Full_day</option>
                    </select>
                  {%endif%}
                
              </td>
              <td>--</td>
              <td>--</td>
            </tr>
       {%endfor%}
      {%endif%}




{%endblock%}